export default function Head() {
	return (
		<>
			<title>O'Waste Dashboard</title>
			<link rel="icon" href="/favicon.ico" type="image/x-icon" />
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
		</>
	);
}

